### ISSUE TITLE
Infografía 

### ISSUE THREAD

**Issue by ghost** [SistemasTecTlaxiaco/infografia-Diego0501#2]
[DiefoFidelSosaCruzInforgrafia.pdf](https://github.com/SistemasTecTlaxiaco/infografia-Diego0501/files/12501506/DiefoFidelSosaCruzInforgrafia.pdf)

**Comment by 23620031** [comment]
REDACCIÓN Y ORTOGRAFÍA 10/10
EXPOSICIÓN DE IDEAS CENTRALES 15/15
ORGANIZACIÓN DE LA INFORMACIÓN 15/15
USO DE IMÁGENES Y COLORES 15/15
PRESENTACIÓN VISUAL 13/15 (elementos visuales poco atractivos)
REFERENCIAS 15/15
PRESENTACIÓN 15/15

CALIFICADO POR EL EQUIPO DE "LÓPEZ  DOMÍNGUEZ ISAÍAS BRAYAN"

**Comment by josealfredo79** [comment]
Bien echo y revisado...
